transit:
  t0: 0.0 # time of inferior conjunction
  per: 2.21857567 # orbital period in days
  rp: 0.1548291121 # planet radius (in units of stellar radii)
  a: 8.9625402483 # semi-major axis (in units of stellar radii)
  inc: 85.71 # orbital inclination (in degrees)
  ecc: 0.0 # eccentricity
  w: 20.0 # longitude of periastron (in degrees)
  u: [0.1, 0.3] # limb darkening coefficients [u1, u2]
  limb_dark: "quadratic" # limb darkening model
classifier:
  type: cnn # [cnn, rf] for Convolutional Neural Network and Random Forest
#assignmnet2 taskG
detection:
  method: rf                 # optional label, not used by code but informative
  kernel: default_rf         # name of the RF configuration
  csv_path: tess_data.csv    # <<< dataset path (required in the assignment)
  n_bins: 1000
  use_scaler: false
  samples_per_class: 350
  n_estimators: 500
  max_depth: null
#task h assignment 2
detection:
  kernel: cnn          # or "rf" when you want RF by default (not used by CLI, but good documentation)
  csv_path: tess_data.csv
  n_bins: 1000
  use_scaler: true
  samples_per_class: 350

  # CNN-specific hyperparameters (Task H)
  epochs: 20
  batch_size: 64
  learning_rate: 0.001
